### ISSUE TITLE
using LegacyString breaks `string(::Char)`

### ISSUE THREAD

**Issue by vtjnash** [JuliaArchive/LegacyStrings.jl#8]
``` julia
ERROR: MethodError: string(::Char) is ambiguous. Candidates:
  string(a::Union{Char,LegacyStrings.ASCIIString,LegacyStrings.UTF8String}...) at /Users/jameson/.julia/v0.6/LegacyStrings/src/utf8.jl:161
  string(a::Union{Char,String}...) at strings/string.jl:179
```

**Comment by martinholters** [comment]
How about just removing `string(a::Union{ByteString,Char}...)`? IIUC, it's just there for performance sake, and correctness should be more important than performance. An alternative could be to rewrite it as `string(a1::ByteString, a::Union{ByteString,Char}...)` to keep the same performance at least for cases where the first argument is not a `Char`. I have no idea whether it is worth it, though.
